name: iot_home
description: A little iot-core project using MQTT and my beagle bone
version: 2.0.0
author: Steve Hamblett <steve.hamblett@linux.com>
homepage: https://github.com/shamblett/iot-home

environment:
  sdk: ">=2.0.0  <3.0.0"

dependencies:
  mqtt_client: '>=3.0.0 <=4.0.0'
  jaguar_jwt: '^2.1.5'
  args: '^1.5.0'
  intl: '^0.15.7'

dev_dependencies:
  test: '^1.3.0'
  coverage: '^0.12.2'
  #dart_dev: '^2.0.0-alpha'
  dart_style: '^1.1.3'
  dartdoc: '^0.20.3'
