name: iot_home
description: A little iot-core project using MQTT and my beagle bone
version: 1.0.0
author: Steve Hamblett <steve.hamblett@linux.com>
homepage: https://github.com/shamblett/iot-home

environment:
  sdk: ">=1.8.0  <2.0.0"

dependencies:
  mqtt_client: ">1.0.0 <2.0.0"
  just_jwt: "^1.3.1"

dev_dependencies:
  test: '^0.12.0'
  coverage: '^0.7.3'
  dart_dev: '^1.0.0'
  dart_style: '>=0.2.0 <0.3.0'
  dartdoc: '>=0.8.0 <=0.10.0'
  
